# Generated by Django 3.2.6 on 2022-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=60)),
                ('last_Name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('street_Address', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('postal_Address', models.CharField(max_length=60)),
            ],
        ),
    ]
