# Generated by Django 3.2.6 on 2022-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=60)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
