# Generated by Django 3.2.6 on 2022-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaresp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
