# Generated by Django 3.2.6 on 2022-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_mpesaresp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaresp',
            name='CheckoutRequestID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpesaresp',
            name='MerchantRequestID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpesaresp',
            name='ResultCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mpesaresp',
            name='ResultDesc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
