# Generated by Django 3.2.6 on 2022-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20220309_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaExprSuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=50, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('TransactionDate', models.CharField(max_length=50, null=True)),
                ('MpesaReceiptNumber', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
