# Generated by Django 3.2.6 on 2022-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_mpesaexprsuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='TransactionDate',
            field=models.IntegerField(null=True),
        ),
    ]
