# Generated by Django 3.2.6 on 2022-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20220309_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesaexprsuc',
            old_name='MpesaReceiptNumber',
            new_name='NMpesaReceiptNumber',
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='Amount',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='PhoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='TransactionDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
