# Generated by Django 3.2.6 on 2022-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20220309_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='TransactionDate',
            field=models.IntegerField(null=True),
        ),
    ]
