# Generated by Django 3.2.6 on 2022-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20220309_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='PhoneNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesaexprsuc',
            name='TransactionDate',
            field=models.BigIntegerField(null=True),
        ),
    ]
