# Generated by Django 3.2.6 on 2022-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20220309_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequestID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=70)),
            ],
        ),
    ]
