# Generated by Django 3.2.6 on 2022-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_checkoutrequestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaexprsuc',
            name='CheckoutRequestID',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
